### ISSUE TITLE
Feature Request: make CTRNAND downloading an option in config file

### ISSUE THREAD

**Issue by sora10pls** [KunoichiZ/lumaupdate#10]
Instead of having the user press (A) + (X) every time they wish to install Luma3DS, check the config file.

If `lumaupdater.cfg` exists on the SD Card (be it on the root or in the `luma` directory), check to see an option for CTRNAND downloading.

If it is set to yes, download to SD Card and CTRNAND.
If it is set to no, download to SD Card *only*.
If it doesn't exist, ask the user (the way it functions now).

Current format:
`payload type = sighax`
`payload path = boot.firm`
`log enable = yes`
`selfupdate = yes`
`backup = yes`

Ideal format proposed by this issue:
`payload type = sighax`
`payload path = boot.firm`
`log enable = yes`
`selfupdate = yes`
`backup = yes`
`ctrnand = yes`

**Comment by KunoichiZ** [comment]
I'm still trying to figure out why lumaupdater.cfg is having issues. For now, this will not be implemented. CTRNAND writing already being optional is good enough for now.

**Comment by sora10pls** [comment]
Any idea what exactly isn't working properly? It's working fine for me, barring self-update.

Personally, I've disabled `log enable` and `backup` as I don't like the extra files on my SD Card, and the latest release acknowledges that they're set to "no" in my config file.

**Comment by KunoichiZ** [comment]
I can't exactly remember why it's not working, but it was giving people who had the .cfg on their SD card from the a9lh days issues as it wouldn't properly write sighax/SIGHAX for the payload type. The CTRNAND writing code isn't even mine, and I would have to ask the author how to change it so that it could properly write to lumaupdater.cfg.
