### ISSUE TITLE
Issues downloading latest Luma3DS

### ISSUE THREAD

**Issue by nickshanks347** [KunoichiZ/lumaupdate#101]
I've attached a screenshot of an error I'm getting when trying to update to Luma3DS 10.3. Please see the attached screenshot.

![image](https://user-images.githubusercontent.com/11299982/158716946-c3e25456-ab01-45d6-a3a7-9c9945600737.jpeg)

**Comment by twinec** [comment]
try updating with universal updater

**Comment by KunoichiZ** [comment]
Why are people still using this? 3ds.hacks.guide has a better method to updating Luma now. LumaUpdater isn't even a part of the guide anymore. Closing this as all developement has stopped on this, in case it wasn't obvious.
