### ISSUE TITLE
MD5 mismatch

### ISSUE THREAD

**Issue by schnuff-dev-personal** [KunoichiZ/lumaupdate#102]
### What model of system are you using?
- [X] Old 3DS
- [ ] Old 3DS XL
- [ ] 2DS (non-XL)
- [ ] New 3DS
- [ ] New 3DS XL
- [ ] New 2DS XL

### What is your current Luma3DS version?
If you are running an hourly version of Luma3DS, please manually update to a stable version as I will no longer deal with people who are using hourlies.

- [ ] Luma3DS v7.1 + boot9strap v1.0/v1.1
- [ ] Luma3DS v8.0 + boot9strap v1.2+
- [ ] Luma3DS v8.1 + boot9strap v1.2+
- [ ] Luma3DS v8.1.1 + boot9strap v1.2+
- [ ] Luma3DS v9.0 + boot9strap v1.2+
- [ ] Luma3DS v9.1 + boot9strap v1.2+
- [X] Luma3DS v10.0+ + boot9strap v1.2+

### What version of Luma Updater are you using?
- [ ] v2.0
- [ ] v2.1
- [ ] v2.1.1
- [ ] v2.1.2
- [ ] v2.2
- [ ] v2.3
- [ ] v2.4
- [ ] v2.5
- [X] v2.6

### How are you running Luma Updater?
- [ ] .cia
- [X] .3dsx + HBL/Rosalina

### What problems are you experiencing?
Please tell us what problems you are facing.

Download fails on a second integrity check
Md5 mismatch

### What is the exact error code you are receiving?
Please give the exact error code the app gives you.

### Steps to reproduce

1. 
2. 
3.

**Comment by megarobohobo** [comment]
Development has stopped on this, so no fix is incoming.

KunoichiZ, you may want to add a warning to the top of README.md, or archive the repo if you don't wanna keep coming in and closing each one of these individual issues.

**Comment by KunoichiZ** [comment]
@megarobohobo I'm about to. This is ridiculous.
