### ISSUE TITLE
Feature request: Universal updater

### ISSUE THREAD

**Issue by d0k3** [KunoichiZ/lumaupdate#12]
I know, this might be a bit much to ask, but nonetheless something that you may want to think about.

By now, the number of relevant (for the common user!) ARM9 software has shrinked dramatically. We've only got Luma 3DS, GodMode9, SafeB9SInstaller left (and D9WIP / HG9 if you believe some users). With things moving as fast as they do, Luma 3DS may need an update when boot9strap updates, and GodMode9 may need an update when Luma 3DS or boot9strap update. This also goes in the other direction.

I also frequently have users asking how to update GodMode9.

Now, my proposal would be to include a small number of selected ARM9 software in Luma Updater, which would be downloaded and set up right inside the Luma 3DS payload folder.

Stable releases for GodMode9:
https://github.com/d0k3/GodMode9/releases

Stable releases for SafeB9SInstaller:
https://github.com/d0k3/SafeB9SInstaller/releases

Hourlies for both (and others):
http://d0k3.secretalgorithm.com/

If you decide to follow up on this, I'd be willing to help should any changes be required on my side.

**Comment by KunoichiZ** [comment]
Someone did already mention this. I told them that I would look into it. My summer classes start next Monday, and I can't guarantee that I will have time to properly look into it, but it is on my list of things to look into. :) And I appreciate you offering to help!

**Comment by KunoichiZ** [comment]
In thinking about it, as much as I would like to implement this in Luma Updater (calling it LU for short), I'm not sure if I can without royally messing something up. I'm still trying to study and learn LU's code. I may, however, attempt to make a separate app that can accomplish this? And if I succeed in that, I'll see what I can do about merging it in with LU.

**Comment by d0k3** [comment]
Adding to this... see this pull request: https://github.com/SciresM/boot9strap/pull/11

Check my last comment there. I know, I am already several steps ahead, but using the bootonce.firm feature (if @SciresM takes it), you could also init the boot9strap update after the Luma 3DS update.

**Comment by KunoichiZ** [comment]
I'll see what I can do, however, I don't have a whole lot of time and I can't guarantee anything.

**Comment by KunoichiZ** [comment]
I just realized this: [MultiUpdater](https://github.com/LiquidFenrir/MultiUpdater) by LiquidFenrir does what you're wanting in that it'll update GM9/H9/D9 and Luma. You could ask Fenrir to see about adding support for bootonce.firm and SafeB9SInstaller.
