### ISSUE TITLE
Advice for getting luma3ds version

### ISSUE THREAD

**Issue by x7l7j8cc** [KunoichiZ/lumaupdate#13]
Hi, ive readed from your latest release:

> Because of the name of the latest stable Luma3DS release, Luma Updater will say "A new stable version of Luma3DS is available" despite you already having the latest version (8.0-21db0d4). This is something I cannot fix until the name of the stable release changes back to the format it was in. Keep checking Luma3DS's releases page to see if a new stable version is actually released.

so, i have an advice for you... in the file "source/release.cpp" , instead of using "name", use "tag_name".
the name can change, but the tag_name remain unchanged, so instead of having "luma3ds v8.0" or future releases, you will always have "v8.0" as before.

**Comment by KunoichiZ** [comment]
Wow, that did fix the issue! Thanks! I will re-upload v2.1.2 with this fix shortly.
