### ISSUE TITLE
Black screen after install luma3ds 8.0 with X+A

### ISSUE THREAD

**Issue by CarterLi** [KunoichiZ/lumaupdate#15]
Power up with pressing Start button and power up without SD card don't work
I don't know what to do but file a issue here. Please help 😭

**Comment by CarterLi** [comment]
Well, after putting `boot.firm` of luma3ds 7.1 into the root folder of my SD card, my 3ds boots again.

**Comment by etward2** [comment]
I have the same problem. What can you do here?
