### ISSUE TITLE
Updater installs dev build when choosing to Install Stable build

### ISSUE THREAD

**Issue by Auscobe** [KunoichiZ/lumaupdate#16]
O3DSXL 11.4 USA B9S 1.2 Luma 8.0

whenever i try to install the latest Stable build from Luma Updater, it "Succeeds" and when i go back into it it shows a dev build next to installed version. should i just get the payload from the releases page and see if that works?

**Comment by KunoichiZ** [comment]
Can you provide a screenshot?

**Comment by Auscobe** [comment]
i just tried, but for some reason the top screen picture became a glitched homebrew picture.

**Comment by KunoichiZ** [comment]
I can't help you if you don't provide proof of some kind.

**Comment by KunoichiZ** [comment]
The string attached to the current installed version is the commit number that corresponds to that release version. It's not a dev build.

**Comment by Auscobe** [comment]
oh.
sorry for that, then.
