### ISSUE TITLE
Update failed luma 8.0 to 8.1

### ISSUE THREAD

**Issue by AtomHare** [KunoichiZ/lumaupdate#22]
Write in the console chat
```
Downloading https://github.com/AuroraWright/luma3DS/releases/download/v8.1/Luma3DSv8.1.7z
Could not get status code
Ret Code: -660561850
FATAL
Could not get sighax payload. . .
```
How I can update ?

**Comment by Mxrk** [comment]
Same error here.

**Comment by KunoichiZ** [comment]
I'm working on it.

**Comment by CodyMKW** [comment]
on my launch 3ds I was able to update from 8.0 to 8.1 just fine

**Comment by KunoichiZ** [comment]
@CodyMKW Can you downgrade back to 8.0 then try to use Luma Updater to update? I agree that it was fine earlier, but I don't know why it's not working now.

**Comment by hax0kartik** [comment]
I don't why its failing for others, mine just worked fine.

**Comment by AtomHare** [comment]
tried to do the update today and worked O_o

**Comment by KunoichiZ** [comment]
Maybe it was a Github issue?

**Comment by hax0kartik** [comment]
Seems like it.

**Comment by AtomHare** [comment]
Yes but thank you for your reactivity KunoichiZ
