### ISSUE TITLE
Lumaupdater 3dsx for HBL doesn't backup = Update failed xD

### ISSUE THREAD

**Issue by InFeX90** [KunoichiZ/lumaupdate#23]
Hello, I downloaded lumaupdater zip, and set it inside the 3ds folder (for the HBL), but after trying to update, it says:

 Update Failed and shows  "BACKUP FAILED" as error.

"Copying /boot.firm to /boot.firm.bak... FATAL
Could not backup /boot.firm (!!), aborting..."

is what it says...

Yes, i'm up to date with B9s (1.2)

**Comment by KunoichiZ** [comment]
I haven't tested the .3dsx version as I don't use it. I can see if Kartik can see if they can fix it.

**Comment by hax0kartik** [comment]
@InFeX90  Could you please upload your log file? Also does it have the same behavior for the CIA version?

**Comment by InFeX90** [comment]
Sure; I made an update; installing the CIA, but for me it's much safer doing it through Rosalina HBL than installing the CIA, you know, hiding the evidence... Anyway here it is:

> Checking for new Luma3DS Updater releases...
> Downloading https://api.github.com/repos/KunoichiZ/lumaupdate/releases/latest...
> Download progress: 5533 / 5533
> Downloaded 5533 bytes
> JSON parsed successfully!
> Release found: v2.1.2
> Changelog found.
> Current updater is already at latest release.
> Trying detection of current payload version...
> 8.1-31e2243
> Downloading https://api.github.com/repos/AuroraWright/Luma3DS/releases/latest...
> Download progress: 4118 / 4118
> Downloaded 4118 bytes
> JSON parsed successfully!
> Release found: 8.1
> Found version: Luma3DSv8.1.7z
> Release description found.
> Downloading http://astronautlevel2.github.io/Luma3DS/lastCommit...
> Download progress: 8 / 8
> Downloaded 8 byte
> Do you want to enable downloading boot.firm on CTR-NAND?
>  Press A + X to enable
>  Press B to disable
> CTR-NAND related operations enabled
> Copying /boot.firm to /boot.firm.bak...
> FATAL
> Couldn't open CTR-NAND for renaming
> Could not backup /boot.firm (!!), aborting...

**Comment by hax0kartik** [comment]
@InFeX90  Please try out this:-

1. Open the Rosalina menu by pressing L + Down + Select
2. Select "Process patches menu" from the list by pressing the A button.
3. Select "Patch FS for Archive checks" and then press B twice to exit the menu.
4. Open hbl and select LumaUpdater.

**Comment by hax0kartik** [comment]
Also are you using some custom title instead of the default title as the base of Rosalina-hbmenu?

**Comment by InFeX90** [comment]
Download Play app, so what should i do? xD open download play app, switch the hbl launcher, and then do what you posted above?

**Comment by hax0kartik** [comment]
Do the above, and then open download play.

**Comment by InFeX90** [comment]
Same results. Didn't work out.

**Comment by hax0kartik** [comment]
Ok try the switching the the Rosalina hb-menu entrypoint to Nintendo-3ds-camera.

**Comment by hax0kartik** [comment]
If I am correct, then this actually not the fault of lumaupdater. Download play doesn't have access to fs:USER which causes the application to not have the correct permission to open CTR-NAND.

**Comment by InFeX90** [comment]
Well, it didn't work out again...

**Comment by hax0kartik** [comment]
Um, do you have hbl_loader or FBI installed?

**Comment by InFeX90** [comment]
You mean the cia file? No, it was Uninstalled by me once i saw another way to prevent or at least decrease the possibility of ban by Nintendo... should I install it?

**Comment by hax0kartik** [comment]
Please install FBI and the switch the hbl entrypoint to it. This worked for me.

**Comment by InFeX90** [comment]
It worked! but if i have to install FBI, my objective for decrease the ban by N, goes to hell...

**Comment by Pirater12** [comment]
@InFeX90 You can use "streetpass mii plaza" instead of FBI

**Comment by InFeX90** [comment]
Lol... Doesn't work...

**Comment by hax0kartik** [comment]
@InFeX90  Select "Patch ARM9 Access" from luma configuration menu and then you will be able to use lumaupdate from any app(tested, works with download play too). 😃

**Comment by InFeX90** [comment]
Great, yeah, you're  right, it worked... so, this doesn't affect my "proposite", right? i mean, can it pass Unnoticed under the N's eye? But also, won't this affect the way i use my 3DS?

**Comment by hax0kartik** [comment]
Afaik, this is undetectable and no this won't affect the way you use you're 3ds

**Comment by InFeX90** [comment]
Ok then, in any case I think I'll activate that option before upgrading and turning it off after. Thanks for the support given to me.
