### ISSUE TITLE
CTR-NAND write denied

### ISSUE THREAD

**Issue by ghost** [KunoichiZ/lumaupdate#24]
Hello, I am attempting to update my Luma to the latest stable version. The update fails and says that it "Couldn't open CTR-NAND for writing." This was not an issue before I updated to B9S from A9LH. Can anyone help?

**Comment by hax0kartik** [comment]
@LingKrauz   Select "Patch ARM9 Access" from luma configuration menu and then you should be able to use lumaupdate's ctrnand functions. 😄

**Comment by ghost** [comment]
Thanks
