### ISSUE TITLE
Request: bump version number

### ISSUE THREAD

**Issue by chenzw95** [KunoichiZ/lumaupdate#26]
May I request that a new release be pushed so as to address issues which inexperienced users accidentally run into, especially the one described in #19 (users running the updater to update from 7.1 to 8.x, which is an incompatible upgrade path)?

I am one of many volunteers in the Nintendo Homebrew discord server, which attends to a huge volume of support requests from users, and this is among the top problems that users come to us to seek assistance for.

**Comment by KunoichiZ** [comment]
I'm currently finishing up my summer semester of college classes. I will push the next version on Monday.

**Comment by KunoichiZ** [comment]
I'm sorry a release has not come out sooner. I'm having issues with my build environment (bannertool is not working anymore for whatever reason so I can't directly build the CIA) and I haven't had time to look into a fix.

**Comment by KunoichiZ** [comment]
Re-opened because a new version is not out due to bugs.

**Comment by chenzw95** [comment]
PR #30 filed, which addresses them, sorry for the delay.

**Comment by Git-Maker** [comment]
it says wrong payload version and sighax does not work. Should I change it some how on the config file to ninhax?

**Comment by KunoichiZ** [comment]
@Git-Maker No. It has to be sighax or SIGHAX, iirc. Download the lumaupdater.cfg file on the repo and try again. Also, this issue does not belong in this issue thread. You should've made your own issue. :/

**Comment by KunoichiZ** [comment]
v2.2 has been released. Let me know of any issues that occur.
