### ISSUE TITLE
Request: Re-enable hourly builds

### ISSUE THREAD

**Issue by Jolty95** [KunoichiZ/lumaupdate#28]
Good afternoon.
I just wanted to ask if luma hourly builds are going to be re-enabled in next lumaupdate version.
Thanks for all :)

**Comment by KunoichiZ** [comment]
No. Too many "bricks" have been reported using the hourlies and Luma Updater. If you want them re-enabled, the source code is public. Anyone can fork it and re-enable it themselves.

Not trying to be rude, but I'm tired of seeing the "brick" reports.

**Comment by Jolty95** [comment]
First thanks for answering :)
I don't think that answer is rude at all and I understand your point of view too. A lot of people always thinks there are "bricks" when 99,99% mistakes are because of them...I know that feeling to dissable hourlies.... Thanks again for your answer, and with your permission (I know the licence of this software but I always like to ask the dev. first :P) I'll re-enabled them in local repo just for me (I really like to be up-to-date :P)
Greetings! :)

**Comment by KunoichiZ** [comment]
Yeah, go right ahead. I don't mind. It's just that noobs who use Luma Updater usually come from following Plailect's 3ds.guide, then attempt to do something stupid and update to something as unstable as an hourly then go to a forum to complain about their system "bricking." For the users who know what they're doing, they can use the hourlies all they want. For the sake of my sanity and the noobs, it won't be re-enabled officially.

**Comment by Jolty95** [comment]
I totally agree with you :)
Thanks for your time!
