### ISSUE TITLE
Unknown or wrong config value a9lh folder type 

### ISSUE THREAD

**Issue by SamBlackChay** [KunoichiZ/lumaupdate#29]
Japanese New 3ds V11.4
Followed the guide to update a9lh to b9s
Last part where I need to install Lumaupdater to update luma I get error
Luma is on v8.1 
Deleted and installed lumaupdater cia twice, still the same

![image](https://user-images.githubusercontent.com/30587630/28765810-388750fa-75ff-11e7-8483-c702bd26f1fd.png)

https://cdn.discordapp.com/attachments/196635695958196224/341461447194181632/20170731_140540.jpg

**Comment by KunoichiZ** [comment]
I assume you figured it out?
