### ISSUE TITLE
Path changer doesn't recognize the new path regardless

### ISSUE THREAD

**Issue by ghost** [KunoichiZ/lumaupdate#3]
So I've tried creating my own payload pathand regardless of what I try, the path patch always fails.

First I tried:
payload path: = luma.firm

Then I tried:
payload path = boot9strap/boot.firm

Last I tried:
payload path = /boot9strap/boot.firm

Lumaupdater detects it as /boot9strap/boot.firm regardless which seems fine. When I try updating to the stable release to test it out, it fails. This payload path seems absolutely correct and it should be working, especially since I looked through Hamcha's wiki and what I'm doing is literally how it's supposed to be. The reason I need the path change is so I can use BootCTR9 to use animated boot screens.

**Comment by KunoichiZ** [comment]
I'm trying to figure out why lumaupdater.cfg is having issues. Until I figure something out, animated boot screens can't happen with this.

**Comment by gnmmarechal** [comment]
This is a strange issue. I've had people complain about path changing not working on my updaters as well. Both Corbenik CFW Updater (and its successor) and StarUpdater seem to suffer from this.

**Comment by KunoichiZ** [comment]
And I wonder why that is. I don't have the time nor patience right now to attempt to figure out anything on it.

**Comment by KunoichiZ** [comment]
This will be addressed in the next release. For now, please see #30.
