### ISSUE TITLE
Bypasses configured proxy

### ISSUE THREAD

**Issue by eku** [KunoichiZ/lumaupdate#33]
### What model of system are you using?
- [ ] Old 3DS
- [x] Old 3DS XL
- [ ] 2DS (non-XL)
- [ ] New 3DS
- [ ] New 3DS XL
- [ ] New 2DS XL

### What is your current Luma3DS version?
If you are running an hourly version of Luma3DS, please manually update to a stable version as I will no longer deal with people who are using hourlies.

- [ ] Luma3DS v7.1 + boot9strap v1.0/v1.1
- [ ] Luma3DS v8.0 + boot9strap v1.2+
- [ ] Luma3DS v8.1 + boot9strap v1.2+
- [ ] Luma3DS v8.1.1 + boot9strap v1.2+
- [x] Luma3DS v9.0 + boot9strap v1.2+

### What version of Luma Updater are you using?
- [ ] v2.0
- [ ] v2.1
- [ ] v2.1.1
- [ ] v2.1.2
- [x] v2.2

### How are you running Luma Updater?
- [x] .cia
- [ ] .3dsx + HBL/Rosalina

### What problems are you experiencing?
Lumaupdate ignores configured proxy from WiFi settings. Fails to connect to api.github.com.

### What is the exact error code you are receiving?
Cannot download files.

### Steps to reproduce

1. Configure a WiFi profile with proxy on 3DS.
2. Start lumaupdater
3. See error message unable to download...

**Comment by KunoichiZ** [comment]
I don't know how to deal with proxies. I don't have an internet connection with a proxy nor do I plan on making one. :/

**Comment by KunoichiZ** [comment]
You need to just download it manually or FTP it in. You are already on the latest stable version and I don't support the nightlies/hourlies. I won't be adding proxy support.
