### ISSUE TITLE
Unable to delete Hamcha's version of Luma so I can install KunochiZ's version

### ISSUE THREAD

**Issue by omar-anwari** [KunoichiZ/lumaupdate#34]
### What model of system are you using?
- [ ] Old 3DS
- [ ] Old 3DS XL
- [ ] 2DS (non-XL)
- [ ] New 3DS
- [x] New 3DS XL
- [ ] New 2DS XL

### What is your current Luma3DS version?
If you are running an hourly version of Luma3DS, please manually update to a stable version as I will no longer deal with people who are using hourlies.

- [ ] Luma3DS v7.1 + boot9strap v1.0/v1.1
- [ ] Luma3DS v8.0 + boot9strap v1.2+
- [ ] Luma3DS v8.1 + boot9strap v1.2+
- [ ] Luma3DS v8.1.1 + boot9strap v1.2+
- [x] Luma3DS v9.0 + boot9strap v1.2+

### What version of Luma Updater are you using?
- [x] v2.0
- [ ] v2.1
- [ ] v2.1.1
- [ ] v2.1.2
- [ ] v2.2

### How are you running Luma Updater?
- [x] .cia
- [ ] .3dsx + HBL/Rosalina

### What problems are you experiencing?
Please tell us what problems you are facing.
When I attempt to delete Hamcha's version of Luma Updater, through the Data Management or FBI, I am greeted with an error saying that I can't delete Luma Updater.
### What is the exact error code you are receiving?
Please give the exact error code the app gives you.
Through Data Management I just get a generic "Could not delete this title". Through FBI I get the error:
Failed to delete title.
Result code: 0xC960454B
Level: Status (25)
Summary: Internal (11)
Module: FS (17)
Des: Bus error/TWL partition invalid (331)

### Steps to reproduce
Attempting to delete through System Settings
1. Enter System Settings
2. Enter Data Management, then 3DS, and then Software
3. Attempt to delete Luma Updater
4. "Could not be deleted" appears

Attempting to delete through FBI
1. Open FBI, cia version
2. Enter Titles section
3. Wait for everything to load in and choose Luma3DS Updater
4. Choose either Delete Title or Delete Title And Ticket
5. Error appears 

### Quick Note
I am able to use all the cfw apps that I have on my 3DS I just can't update Luma to the latest version

**Comment by KunoichiZ** [comment]
I cannot help you with this issue other than tell you this: try using a different SD card. If that doesn't work, ask in [FBI's issues](https://github.com/Steveice10/FBI/issues). This may be about Luma Updater, but unless you have an in-app issue, I cannot help you further.

**Comment by omar-anwari** [comment]
Alright thanks Kunoichi.
