### ISSUE TITLE
(PLEASE READ) Before you make an issue stating that the app doesn't work anymore... (PLEASE READ)

### ISSUE THREAD

**Issue by KunoichiZ** [KunoichiZ/lumaupdate#35]
I am aware of this fact. I am trying to work on a fix with some help. Please have some patience. 

Any issues that show up after this one will be immediately closed as I see them. This is your only warning.

**Comment by iSharingan** [comment]
out of curiosity, is there a way/guide to manually updating in the meantime? I'm bringing my 2DS that I haven't touched since 11.3 up and would rather not blackscreen (if that's even happens any more) after updating the system to the latest.

**Comment by KunoichiZ** [comment]
New version released. See version 2.3
