### ISSUE TITLE
"Unknown or wrong config value: 'a9lh' for payload type

### ISSUE THREAD

**Issue by antivenom03** [KunoichiZ/lumaupdate#39]
### What model of system are you using?
- [ ] Old 3DS
- [x] Old 3DS XL
- [ ] 2DS (non-XL)
- [ ] New 3DS
- [ ] New 3DS XL
- [ ] New 2DS XL

### What is your current Luma3DS version?
If you are running an hourly version of Luma3DS, please manually update to a stable version as I will no longer deal with people who are using hourlies.

- [ ] Luma3DS v7.1 + boot9strap v1.0/v1.1
- [ ] Luma3DS v8.0 + boot9strap v1.2+
- [ ] Luma3DS v8.1 + boot9strap v1.2+
- [ ] Luma3DS v8.1.1 + boot9strap v1.2+
- [x] Luma3DS v9.0 + boot9strap v1.2+

### What version of Luma Updater are you using?
- [ ] v2.0
- [ ] v2.1
- [ ] v2.1.1
- [ ] v2.1.2
- [ ] v2.2
- [x] v2.3

### How are you running Luma Updater?
- [x] .cia
- [ ] .3dsx + HBL/Rosalina

### What problems are you experiencing?
Please tell us what problems you are facing.
I am thrown this error whenever i launch your lumaupdater

### What is the exact error code you are receiving?
Please give the exact error code the app gives you.
"Unknown or wrong config value: 'a9lh' for payload type

### Steps to reproduce

1. open lumaupdater
2. 
3.

**Comment by KunoichiZ** [comment]
From the release notes of previous releases: 

"If you get stuck on the loading configuration file or get an error message such as "Unknown or wrong config value", either delete the lumaupdater.cfg file on the root of your SD card or change the payload type in the first line of lumaupdater.cfg to payload type = SIGHAX and payload path = boot.firm."
