### ISSUE TITLE
Luma Updater hangs at "Checking for an updated updater..."

### ISSUE THREAD

**Issue by britiscurious** [KunoichiZ/lumaupdate#40]
### What model of system are you using?
- [ ] Old 3DS
- [ ] Old 3DS XL
- [ ] 2DS (non-XL)
- [ ] New 3DS
- [x] New 3DS XL
- [ ] New 2DS XL

### What is your current Luma3DS version?
If you are running an hourly version of Luma3DS, please manually update to a stable version as I will no longer deal with people who are using hourlies.

- [ ] Luma3DS v7.1 + boot9strap v1.0/v1.1
- [ ] Luma3DS v8.0 + boot9strap v1.2+
- [ ] Luma3DS v8.1 + boot9strap v1.2+
- [ ] Luma3DS v8.1.1 + boot9strap v1.2+
- [x] Luma3DS v9.0 + boot9strap v1.2+

### What version of Luma Updater are you using?
- [ ] v2.0
- [ ] v2.1
- [ ] v2.1.1
- [ ] v2.1.2
- [ ] v2.2
- [x] v2.3

### How are you running Luma Updater?
- [x] .cia
- [x] .3dsx + HBL/Rosalina

### What problems are you experiencing?
System freezes when Luma Updater is "Checking for an updated updater..."

Upper screen shows:

Loading Luma3DS Updater
#######
Checking for an updated updater...

(progress bar is at that position)

Lower screen shows:

Configuration file loaded successfully.
Trying detection of current updater install...
Checking for new Luma3DS Updater releases...
Downloading https://api.github.com/repos/KunoichiZ/lumaupdate/releases/latest...

LumaUpdater.log is emtpy.

### What is the exact error code you are receiving?
No error code. Device is froozen.

### Steps to reproduce

1. Launch Luma Updater (cia or 3dsx)
2. 
3.

**Comment by KunoichiZ** [comment]
If you launched Luma Updater right after turning on your system, wait until the system connects to the internet then launch the Updater. You shouldn't be receiving an error.

**Comment by britiscurious** [comment]
That's not the solution for my issue. lumupdater works on 2 of 3 of my Nintendo 3DS systems. One permanetly shows the described behavior. Multiple re-installation attempts. The result remains the same. Also internet connection is already established when starting lumaupdater.

**Comment by KunoichiZ** [comment]
I don’t know what to tell you. This issue doesn’t have anything to do with the app. The issue is on your 3DS.
