### ISSUE TITLE
Help Please

### ISSUE THREAD

**Issue by Flanker666** [KunoichiZ/lumaupdate#41]
### What model of system are you using?
- [ ] New 3DS XL

### What is your current Luma3DS version?
- [ ] Luma3DS v7.1 + boot9strap v1.0/v1.1

### What version of Luma Updater are you using?
- [ ] v2.3

### How are you running Luma Updater?
- [ ] .cia

### What problems are you experiencing?
I updated my hacked New 3ds XL to the latest ver. 11.8.0-41E. I didn't have the Luma Updater before. So, now, when I turn on my 3ds, I must go to Luma to reach the 3ds Home menu. I installed the Luma Updater, it says there's an update for it, but it says I need to update boot9strap first. I don't understand because I've got boot9strap's latest updates.

### What is the exact error code you are receiving?
Reason for failure: INCOMPATIBLE UPDATE

### Steps to reproduce

1. 
2. 
3.

**Comment by KunoichiZ** [comment]
Use Luma v9.1. https://github.com/AuroraWright/Luma3DS/releases/tag/v9.1
