### ISSUE TITLE
Issue with update Luma3DS v10

### ISSUE THREAD

**Issue by LiloBzH** [KunoichiZ/lumaupdate#43]
Hello

Maybe becase it's ZIP file and not a Z file no ?

Same problem with an NEW 3DS XL / NEW 2DS XL

> Error : Could not open open archive

**Comment by Brookybalore** [comment]
Hey my 3ds is having trouble updating to the latest Luma sadly

**Comment by KunoichiZ** [comment]
A fix is in progress. Please have patience. Thanks!

**Comment by KunoichiZ** [comment]
[https://github.com/KunoichiZ/lumaupdate/releases/tag/v2.4](https://github.com/KunoichiZ/lumaupdate/releases/tag/v2.4)
