### ISSUE TITLE
Luma3DS latest update to 10.0

### ISSUE THREAD

**Issue by Brookybalore** [KunoichiZ/lumaupdate#45]
I have a New 3DS XL
Current Luma version is v9.1
I am not an hourly user

And I'm not getting an error code.

My current Luma updater which is v2.3 is failing to download the latest update and my payload type is SIGHAX yet when it failed it said it couldn't find SIGHAX despite the fact it's there

I have yet to update my 3ds because I usually update Luma first before hand. Please help me

**Comment by Brookybalore** [comment]
Just found out Luma updater (latest) is actually not supporting the latest update for Luma. I have to manually update it. Thank you for your time

**Comment by KunoichiZ** [comment]
A fix is in progress. Please have patience. Thanks!

**Comment by Brookybalore** [comment]
I actually updated it manually and it worked. Thank you for your time and response I hope updater will be fixed for future updates.

**Comment by KunoichiZ** [comment]
Yes the update should be fixed for future updates soon.

**Comment by KunoichiZ** [comment]
[https://github.com/KunoichiZ/lumaupdate/releases/tag/v2.4](https://github.com/KunoichiZ/lumaupdate/releases/tag/v2.4)
