### ISSUE TITLE
Install fails

### ISSUE THREAD

**Issue by sgtmcbrinn** [KunoichiZ/lumaupdate#47]
### What model of system are you using?
- [ ] Old 3DS
- [ ] Old 3DS XL
- [ ] 2DS (non-XL)
- [ X] New 3DS
- [ ] New 3DS XL
- [ ] New 2DS XL

### What is your current Luma3DS version?
If you are running an hourly version of Luma3DS, please manually update to a stable version as I will no longer deal with people who are using hourlies.

- [ ] Luma3DS v7.1 + boot9strap v1.0/v1.1
- [ ] Luma3DS v8.0 + boot9strap v1.2+
- [ ] Luma3DS v8.1 + boot9strap v1.2+
- [ ] Luma3DS v8.1.1 + boot9strap v1.2+
- [ ] Luma3DS v9.0 + boot9strap v1.2+
- [X ] Luma3DS v9.1 + boot9strap v1.2+

### What version of Luma Updater are you using?
- [ ] v2.0
- [ ] v2.1
- [ ] v2.1.1
- [ ] v2.1.2
- [ ] v2.2
- [X ] v2.3

### How are you running Luma Updater?
- [ X] .cia
- [ ] .3dsx + HBL/Rosalina

### What problems are you experiencing?
Please tell us what problems you are facing.
CIA INSTALL FAILED
### What is the exact error code you are receiving?
Please give the exact error code the app gives you.
Cannot write CIA data to handle Ret code : d8a08002
### Steps to reproduce

1. Launch Luma update cia from 3ds home
2. Press A to allow update
3. Update downloads and extracts, but fails to install

**Comment by sgtmcbrinn** [comment]
I should mention the install for the 2.4 update is failing, not the luma 10.0 update
Edit: The first time I updated it was successful on both my 3ds XL and new 3ds, both still say they're on 2.3. My guess is the update did work which is why trying to update when it asks is causing it to fail but its mistakingly still showing as 2.3

Updating to luma 10.0 on both 3ds' has worked.

So my guess is it's just an error with lumaupdater thinking it's the wrong version when it is actually 2.4.
![15618479737843956177014900156407](https://user-images.githubusercontent.com/5675752/60390122-359a8800-9ac7-11e9-99dd-47a5fa5692b7.jpg)

**Comment by baltimoresports** [comment]
Same issue. I even manual downloaded the CIA and installed it, but it still shows the older version.

**Comment by jaysonanimations** [comment]
I'm on a 2dd and it won't update

**Comment by sks316** [comment]
On my end, the update installs successfully but the version number is incorrect and lumaupdate wants to update again.
Luma3DS updates successfully.
New3DS XL with Luma3DS 10.0, CIA version

**Comment by jaysonanimations** [comment]
Mine just says installed failed and then does nothing

**Comment by uaevuon** [comment]
v2.4 says it's v2.3 in updater, so it keeps trying to update same version.

**Comment by jaysonanimations** [comment]
It never worked though

**Comment by duelistjp** [comment]
i have this same issue.  if i tell it to continue without updating it shows the version as 2.3.something

**Comment by KunoichiZ** [comment]
A fix is in progress. Please have patience.

**Comment by KunoichiZ** [comment]
Everything should now be working properly. Sorry for the inconvenience!

**Comment by baltimoresports** [comment]
Thank you for all the hard work!
