### ISSUE TITLE
Update to 2.4 nor luma 10.0.1 works

### ISSUE THREAD

**Issue by JaySea77** [KunoichiZ/lumaupdate#48]
### What model of system are you using?
- [ ] Old 3DS
- [ ] Old 3DS XL
- [ ] 2DS (non-XL)
- [ ] New 3DS
- [x] New 3DS XL
- [ ] New 2DS XL

### What is your current Luma3DS version?
If you are running an hourly version of Luma3DS, please manually update to a stable version as I will no longer deal with people who are using hourlies.

- [ ] Luma3DS v7.1 + boot9strap v1.0/v1.1
- [ ] Luma3DS v8.0 + boot9strap v1.2+
- [ ] Luma3DS v8.1 + boot9strap v1.2+
- [ ] Luma3DS v8.1.1 + boot9strap v1.2+
- [ ] Luma3DS v9.0 + boot9strap v1.2+
- [x] Luma3DS v9.1 + boot9strap v1.2+

### What version of Luma Updater are you using?
- [ ] v2.0
- [ ] v2.1
- [ ] v2.1.1
- [ ] v2.1.2
- [ ] v2.2
- [x] v2.3

### How are you running Luma Updater?
- [ ] .cia
- [x] .3dsx + HBL/Rosalina

### What problems are you experiencing?
Please tell us what problems you are facing.

Update to updater 2.4 nor update to Luma 10.0.1 work. In both cases the extract of the zip file fails. For updater 22.4 :
Extracting lumaupdater.3dsx[ERR]
FATAL: Could not find 3Ds/lumaupdater/lumaupdater.3dsx in zip file

With Luma 10.0.1 (with skipping updater update):
Top screen:
Reason for failure: DOWNLOAD FAILED
Bottom screen:
Extracting payload [ERR]
FATAL: Could not open archive (SzArEx_Open)
FATAL
Could not get sighax payload...

### What is the exact error code you are receiving?
Please give the exact error code the app gives you.

See above

### Steps to reproduce
Just run 2.3 and try to either update to 2.4 or use 2.3 to update luma.

**Comment by KunoichiZ** [comment]
Should be fixed now. It was a mistake on my part as I didn't upload all of the files in the release to match how the app looks for it.

**Comment by JaySea77** [comment]
Update to 2.4 worked and update to 10.0.1 afterwards worked aswell. Thanks :)

**Comment by KunoichiZ** [comment]
You're welcome! :)
