### ISSUE TITLE
Luma update fail 

### ISSUE THREAD

**Issue by Zemogiter** [KunoichiZ/lumaupdate#50]
### What model of system are you using?
- [ ] Old 3DS
- [ ] Old 3DS XL
- [ ] 2DS (non-XL)
- [ ] New 3DS
- [x] New 3DS XL
- [ ] New 2DS XL

### What is your current Luma3DS version?
If you are running an hourly version of Luma3DS, please manually update to a stable version as I will no longer deal with people who are using hourlies.

- [ ] Luma3DS v7.1 + boot9strap v1.0/v1.1
- [ ] Luma3DS v8.0 + boot9strap v1.2+
- [ ] Luma3DS v8.1 + boot9strap v1.2+
- [ ] Luma3DS v8.1.1 + boot9strap v1.2+
- [ ] Luma3DS v9.0 + boot9strap v1.2+
- [x] Luma3DS v9.1 + boot9strap v1.2+

### What version of Luma Updater are you using?
- [ ] v2.0
- [ ] v2.1
- [ ] v2.1.1
- [ ] v2.1.2
- [ ] v2.2
- [ ] v2.3
- [x] v2.4

### How are you running Luma Updater?
- [x] .cia
- [ ] .3dsx + HBL/Rosalina

### What problems are you experiencing?
Download of Luma3DSv10.0.1.zip fails with the error below
### What is the exact error code you are receiving?
Please give the exact error code the app gives you.

Could not get location header for 3xx reply
Return code: ded92
FATAL
### Steps to reproduce

1. Launch via version of Luna updater 2.4
2. Select install stable version 
3. Pressed b to not download to ctrl nand

**Comment by KunoichiZ** [comment]
Refer to issue #49. Closing.
