### ISSUE TITLE
Error luma update v2.4

### ISSUE THREAD

**Issue by CHITAXD29** [KunoichiZ/lumaupdate#51]
### What model of system are you using?
- [x] Old 3DS
- [ ] Old 3DS XL
- [ ] 2DS (non-XL)
- [ ] New 3DS
- [ ] New 3DS XL
- [ ] New 2DS XL

### What is your current Luma3DS version?
If you are running an hourly version of Luma3DS, please manually update to a stable version as I will no longer deal with people who are using hourlies.

- [ ] Luma3DS v7.1 + boot9strap v1.0/v1.1
- [ ] Luma3DS v8.0 + boot9strap v1.2+
- [ ] Luma3DS v8.1 + boot9strap v1.2+
- [ ] Luma3DS v8.1.1 + boot9strap v1.2+
- [ ] Luma3DS v9.0 + boot9strap v1.2+
- [x] Luma3DS v9.1 + boot9strap v1.2+
- [ ] Luma3DS v10.0+ + boot9strap v1.2+

### What version of Luma Updater are you using?
- [ ] v2.0
- [ ] v2.1
- [ ] v2.1.1
- [ ] v2.1.2
- [ ] v2.2
- [ ] v2.3
- [x] v2.4
### How are you running Luma Updater?
- [x] .cia
- [ ] .3dsx + HBL/Rosalina

### What problems are you experiencing?
Please tell us what problems you are facing.
-Al intentar actualizar LumaUpdater a la versión 2.5, obtengo: Actualización fallida, Motivo del error: DESCARGA FALLIDA, FATAL: no se pudo obtener el encabezado de ubicación para la respuesta 3xx, código Ret: ded92

### What is the exact error code you are receiving?
Please give the exact error code the app gives you. 

Ded92

### Steps to reproduce

1. 
2. 
3.

**Comment by KunoichiZ** [comment]
Please manually update to v2.5. This has been fixed.

**Comment by CHITAXD29** [comment]
> Actualice manualmente a v2.5. Esto ha sido arreglado.

Sorry for the inconvenience, but could you tell me how to update it manually?

**Comment by KunoichiZ** [comment]
Install the cia provided in the releases tab.
