### ISSUE TITLE
Error updating

### ISSUE THREAD

**Issue by blackout5400x** [KunoichiZ/lumaupdate#52]
### What model of system are you using?
- [ ] Old 3DS
- [ ] Old 3DS XL
- [ ] 2DS (non-XL)
- [ ] New 3DS
- [ ] New 3DS XL
- [check ] New 2DS XL

### What is your current Luma3DS version?
If you are running an hourly version of Luma3DS, please manually update to a stable version as I will no longer deal with people who are using hourlies.

- [ ] Luma3DS v7.1 + boot9strap v1.0/v1.1
- [ ] Luma3DS v8.0 + boot9strap v1.2+
- [ ] Luma3DS v8.1 + boot9strap v1.2+
- [ ] Luma3DS v8.1.1 + boot9strap v1.2+
- [ ] Luma3DS v9.0 + boot9strap v1.2+
- [ ] Luma3DS v9.1 + boot9strap v1.2+
- [check ] Luma3DS v10.0+ + boot9strap v1.2+

### What version of Luma Updater are you using?
- [ ] v2.0
- [ ] v2.1
- [ ] v2.1.1
- [ ] v2.1.2
- [ ] v2.2
- [check ] v2.3

### How are you running Luma Updater?
- [check ] .cia
- [ ] .3dsx + HBL/Rosalina

### What problems are you experiencing?
Please tell us what problems you are facing.

### What is the exact error code you are receiving?
Please give the exact error code the app gives you.

"Could not get location header for 3xx reply"
Ret Code: ded92

### Steps to reproduce

1. 
2. 
3.

**Comment by KunoichiZ** [comment]
v2.5 fixes this. Please manually update.

**Comment by blackout5400x** [comment]
ok thank you

**Comment by blackout5400x** [comment]
how do i do that?

**Comment by KunoichiZ** [comment]
Install the cia provided.

**Comment by blackout5400x** [comment]
ok
