### ISSUE TITLE
Failed to update updater

### ISSUE THREAD

**Issue by Runiky** [KunoichiZ/lumaupdate#55]
### What model of system are you using?
- [x] Old 3DS
- [ ] Old 3DS XL
- [ ] 2DS (non-XL)
- [ ] New 3DS
- [ ] New 3DS XL
- [ ] New 2DS XL

### What is your current Luma3DS version?
If you are running an hourly version of Luma3DS, please manually update to a stable version as I will no longer deal with people who are using hourlies.

- [ ] Luma3DS v7.1 + boot9strap v1.0/v1.1
- [ ] Luma3DS v8.0 + boot9strap v1.2+
- [ ] Luma3DS v8.1 + boot9strap v1.2+
- [ ] Luma3DS v8.1.1 + boot9strap v1.2+
- [ ] Luma3DS v9.0 + boot9strap v1.2+
- [ ] Luma3DS v9.1 + boot9strap v1.2+
- [x] Luma3DS v10.0+ + boot9strap v1.2+

### What version of Luma Updater are you using?
- [ ] v2.0
- [ ] v2.1
- [ ] v2.1.1
- [ ] v2.1.2
- [ ] v2.2
- [ ] v2.3
v2.4
### How are you running Luma Updater?
- [ ] .cia
- [x] .3dsx + HBL/Rosalina

### What problems are you experiencing?
Please tell us what problems you are facing.
Cannot download to the newest version of the updater to v.2.5
### What is the exact error code you are receiving?
Please give the exact error code the app gives you.
ded92 / FATAL: Could not get Location header for 3xx reply
### Steps to reproduce

1. click update the updater
2. get the error?
3.

**Comment by hax0kartik** [comment]
#53

**Comment by Runiky** [comment]
Oh thanks
