### ISSUE TITLE
cant update bruh

### ISSUE THREAD

**Issue by Whiteweek** [KunoichiZ/lumaupdate#56]
### What model of system are you using?
- [x] New 2DS XL

### What is your current Luma3DS version?
If you are running an hourly version of Luma3DS, please manually update to a stable version as I will no longer deal with people who are using hourlies.

- [ ] Luma3DS v7.1 + boot9strap v1.0/v1.1
- [ ] Luma3DS v8.0 + boot9strap v1.2+
- [ ] Luma3DS v8.1 + boot9strap v1.2+
- [ ] Luma3DS v8.1.1 + boot9strap v1.2+
- [ ] Luma3DS v9.0 + boot9strap v1.2+
- [x] Luma3DS v10.0+ + boot9strap v1.2+

### What version of Luma Updater are you using?
- [ ] v2.0
- [ ] v2.1
- [ ] v2.1.1
- [ ] v2.1.2
- [ ] v2.2
- [ ] v2.3
- [x] v2.4
- [ ] v2.5

### How are you running Luma Updater?
- [x] .cia
- [ ] .3dsx + HBL/Rosalina

### What problems are you experiencing?
Please tell us what problems you are facing.

Can't update.

### What is the exact error code you are receiving?
Please give the exact error code the app gives you.

ded92

### Steps to reproduce

1. 
2. 
3.

**Comment by KunoichiZ** [comment]
#53
