### ISSUE TITLE
Luma wont update- 3ds won't stream to PC.

### ISSUE THREAD

**Issue by ItsTenshi** [KunoichiZ/lumaupdate#57]
### What model of system are you using?
- [ ] New 3DS XL

### What is your current Luma3DS version?
If you are running an hourly version of Luma3DS, please manually update to a stable version as I will no longer deal with people who are using hourlies.

- [ ] Luma3DS v7.1 + boot9strap v1.0/v1.1
- [ ] Luma3DS v8.0 + boot9strap v1.2+
- [ ] Luma3DS v8.1 + boot9strap v1.2+
- [ ] Luma3DS v8.1.1 + boot9strap v1.2+
- [ ] Luma3DS v9.0 + boot9strap v1.2+
- [ ] Luma3DS v9.1 + boot9strap v1.2+
- [ ] Luma3DS v10.0+ + boot9strap v1.2+
I am not sure how do i check?

### What version of Luma Updater are you using?
- [ ] v2.4

### How are you running Luma Updater?
- [ ] .cia

### What problems are you experiencing?
Please tell us what problems you are facing.
Will not update

### What is the exact error code you are receiving?
Please give the exact error code the app gives you.
Reason for failure: DOWNLOAD FAILED

### Steps to reproduce

1. Opened luma updater
2. selected update
3. download failed

**Comment by KunoichiZ** [comment]
#53
