### ISSUE TITLE
Not updating 

### ISSUE THREAD

**Issue by pohhlo** [KunoichiZ/lumaupdate#58]
##### If you want to create a request, please delete all text after this message.
-->

### What model of system are you using?
- [ ] Old 3DS
- [ ] Old 3DS XL
- [ ] 2DS (non-XL)
- [ ] New 3DS
- [.] New 3DS XL
- [ ] New 2DS XL

### What is your current Luma3DS version?
If you are running an hourly version of Luma3DS, please manually update to a stable version as I will no longer deal with people who are using hourlies.

Not sure

- [ ] Luma3DS v7.1 + boot9strap v1.0/v1.1
- [ ] Luma3DS v8.0 + boot9strap v1.2+
- [ ] Luma3DS v8.1 + boot9strap v1.2+
- [ ] Luma3DS v8.1.1 + boot9strap v1.2+
- [ ] Luma3DS v9.0 + boot9strap v1.2+
- [ ] Luma3DS v9.1 + boot9strap v1.2+
- [ ] Luma3DS v10.0+ + boot9strap v1.2+

### What version of Luma Updater are you using?
- [ ] v2.0
- [ ] v2.1
- [ ] v2.1.1
- [ ] v2.1.2
- [ ] v2.2
- [ ] v2.3
- [.] v2.4
- [ ] v2.5

### How are you running Luma Updater?
- [.] .cia
- [ ] .3dsx + HBL/Rosalina

### What problems are you experiencing?
Please tell us what problems you are facing.
       Tapped to update but update keeps failing 
“Reason-Download Failed”
“Fatal: Couldn’t get location header for 3xx reply”
“Rey code: ded92” 
### What is the exact error code you are receiving?
Please give the exact error code the app gives you.

### Steps to reproduce
Idk how to reproduce this issue
1. 
2. 
3.

**Comment by pohhlo** [comment]
Don’t know how to fix it

**Comment by KunoichiZ** [comment]
#53
