### ISSUE TITLE
doesn't read current installed version properly

### ISSUE THREAD

**Issue by zweilous** [KunoichiZ/lumaupdate#6]
with v2.1 of this app, it detects commit "c73fec4" as "c73fec46."
i then installed the latest hourly; at this time of writing it's commit "a187c0c." the app read the current installed version as "a187c0c7" so it'll keep saying that a new hourly is available

**Comment by KunoichiZ** [comment]
I don't even know where that extra number is coming from. If I can't figure out where it's coming from, I'll just disable the commit being at the end. It even did this on v1.4.2 (Hamcha's last version), before I even started working on it, so it's something that Hamcha did).

**Comment by gnmmarechal** [comment]
It isn't wrong. Take a look at the full commit sha:

a187c0c7cec07790401ac81d56e77d55fed2b328
just remove the last character.

**Comment by KunoichiZ** [comment]
@gnmmarechal So that's what it is! Thanks for that!
