### ISSUE TITLE
An error with the updates

### ISSUE THREAD

**Issue by LuSamus** [KunoichiZ/lumaupdate#66]
### What model of system are you using?
- [x] Old 3DS
- [ ] Old 3DS XL
- [ ] 2DS (non-XL)
- [ ] New 3DS
- [ ] New 3DS XL
- [ ] New 2DS XL

### What is your current Luma3DS version?
If you are running an hourly version of Luma3DS, please manually update to a stable version as I will no longer deal with people who are using hourlies.

- [ ] Luma3DS v7.1 + boot9strap v1.0/v1.1
- [ ] Luma3DS v8.0 + boot9strap v1.2+
- [ ] Luma3DS v8.1 + boot9strap v1.2+
- [ ] Luma3DS v8.1.1 + boot9strap v1.2+
- [ ] Luma3DS v9.0 + boot9strap v1.2+
- [x] Luma3DS v9.1 + boot9strap v1.2+
- [ ] Luma3DS v10.0+ + boot9strap v1.2+

### What version of Luma Updater are you using?
- [ ] v2.0
- [ ] v2.1
- [ ] v2.1.1
- [ ] v2.1.2
- [ ] v2.2
- [x] v2.3
- [ ] v2.4
- [ ] v2.5

### How are you running Luma Updater?
- [x] .cia
- [ ] .3dsx + HBL/Rosalina

### What problems are you experiencing?
I have two problems but they're similar, I want to update Luma Updater and Luma3DS but it doesn't work.

### What is the exact error code you are receiving?
When I try updating both things, the ret code is ded92.

### Steps to reproduce

1. I open the Luma Updater and this check for updates.
2. I select update and I get the error.
3. If I don't update Luma Updater, it continues normally.
4. I update the Luma3DS and I get the same error.

I don't speak English, I tried being direct and I hope that I had explained.

**Comment by KunoichiZ** [comment]
#53.

**Comment by miftahafina** [comment]
You have to install via .cia
