### ISSUE TITLE
LumaUpdate sometimes seem to not be able to retrieve correct info

### ISSUE THREAD

**Issue by xpirad** [KunoichiZ/lumaupdate#70]
I'm using luma updater v2.5 (cia) and luma3ds v10.1-31891ef
I'm using a proxy to access internet.

Luma updater says:

Current installed version : 10.1-31891ef
Latest version (Github):                                 (yes its empty!)

A new stable version of Luma3DS is available (but i'm already on the latest stable version???)

On the lower screen:

No release notes found for v(v is written in green)

**Comment by xpirad** [comment]
I find this to happen about 50% of times. Sometimes LumaUpdate works alright and shows the correct info, sometimes it doesn't. Can you consider adding extra verification for the info retrieved?

Also, will the downloaded firm file be verified in case it is corrupted or only partially downloaded?

Thanks!!!

**Comment by SKCro** [comment]
Maybe try turning off your proxy settings temporarily? The proxy may be interfering with LumaUpdate somehow...

**Comment by xpirad** [comment]
I'd want to, except i can't access internet without proxy...

**Comment by KunoichiZ** [comment]
So we can’t seem to figure out why this happens.

**Comment by xpirad** [comment]
Does LumaUpdate support system proxy?

**Comment by KunoichiZ** [comment]
I am unsure if it does. I want to say no.

**Comment by xpirad** [comment]
Will you, um, consider adding support for it?

**Comment by eku** [comment]
@SKCro the updater ignores the proxy settings in the wifi profile. See #33.

**Comment by KunoichiZ** [comment]
@xpirad We don’t even know if this issue is related to proxies or not. A friend of mine had this issue and he’s not using proxied internet. We don’t know what causes it.

**Comment by xpirad** [comment]
That is weird

**Comment by KunoichiZ** [comment]
I’m not ruling out proxied internet causing this issue for other people, however. I just don’t know.

**Comment by kescherCode** [comment]
I am not using any sort of proxy, but the info still arrives wrongly half the time.

**Comment by AwesomeLuigi** [comment]
I am having the same issue here, I am running Luma3DS on my Old 3DS and currently installed it using SIGHax and still doesn't work still.

**Comment by KunoichiZ** [comment]
Closing as v2.6 has been released.
