### ISSUE TITLE
Old 3ds Failed to update Luma 10.1.3

### ISSUE THREAD

**Issue by fullskull** [KunoichiZ/lumaupdate#71]
### What model of system are you using?
- [x] Old 3DS
- [ ] Old 3DS XL
- [ ] 2DS (non-XL)
- [ ] New 3DS
- [ ] New 3DS XL
- [ ] New 2DS XL

### What is your current Luma3DS version?
If you are running an hourly version of Luma3DS, please manually update to a stable version as I will no longer deal with people who are using hourlies.

- [ ] Luma3DS v7.1 + boot9strap v1.0/v1.1
- [x] Luma3DS v8.0 + boot9strap v1.2+
- [ ] Luma3DS v8.1 + boot9strap v1.2+
- [ ] Luma3DS v8.1.1 + boot9strap v1.2+
- [ ] Luma3DS v9.0 + boot9strap v1.2+
- [ ] Luma3DS v9.1 + boot9strap v1.2+
- [ ] Luma3DS v10.0+ + boot9strap v1.2+

### What version of Luma Updater are you using?
- [ ] v2.0
- [ ] v2.1
- [ ] v2.1.1
- [ ] v2.1.2
- [ ] v2.2
- [ ] v2.3
- [x] v2.4
- [ ] v2.5

### How are you running Luma Updater?
- [x] .cia
- [ ] .3dsx + HBL/Rosalina

### What problems are you experiencing?
Please tell us what problems you are facing.
DOWNLOAD FAILED
### What is the exact error code you are receiving?
Please give the exact error code the app gives you.
ded92
### Steps to reproduce

1. Run Luma Updater .cia
2. Dont update (to v2.5) and continue
3. Install stable version (10.1.3)

**Comment by KunoichiZ** [comment]
#53

**Comment by fullskull** [comment]
To solve this problem, first unistall the current luma updater v2.4 and download luma 2.5 zip
https://github.com/KunoichiZ/lumaupdate/releases/download/v2.5/lumaupdater-2.5.zip
Copy and paste to your 3d sd memory (copy the files from inside "3ds" binder of the .zip to the binder "3ds" of the sd, and the another files of the .zip copy and paste to the root of your 3ds sd)  Extract the sd and put on your 3ds, turn it on, and go to FBI for install the cia file. When its done, go to the luma updater icon and run the app and follow the steps to update Luma. Thanks.
