### ISSUE TITLE
LumaUpdater Error

### ISSUE THREAD

**Issue by williegpks** [KunoichiZ/lumaupdate#74]
### What model of system are you using?
- [ ] Old 3DS
- [ ] Old 3DS XL
- [ ] 2DS (non-XL)
- [ ] New 3DS
- [ ] New 3DS XL
- [x ] New 2DS XL

### What is your current Luma3DS version?
If you are running an hourly version of Luma3DS, please manually update to a stable version as I will no longer deal with people who are using hourlies.

- [ ] Luma3DS v7.1 + boot9strap v1.0/v1.1
- [ ] Luma3DS v8.0 + boot9strap v1.2+
- [ ] Luma3DS v8.1 + boot9strap v1.2+
- [ ] Luma3DS v8.1.1 + boot9strap v1.2+
- [ ] Luma3DS v9.0 + boot9strap v1.2+
- [ ] Luma3DS v9.1 + boot9strap v1.2+
- [ x] Luma3DS v10.0.1+ + boot9strap v1.2+

### What version of Luma Updater are you using?
- [ ] v2.0
- [ ] v2.1
- [ ] v2.1.1
- [ ] v2.1.2
- [ ] v2.2
- [ ] v2.3
- [x (i think) ] v2.4
- [ ] v2.5

### How are you running Luma Updater?
- [ x] .cia
- [ ] .3dsx + HBL/Rosalina

### What problems are you experiencing?
When i load up luma-updater it tells me i can update to v2.5. when i update it tells me 
" Update failed

Something went wrong while trying to update. see the screen below for details.

Reason for failure: DOWNLOAD FAILED

FATAL: Could not get Location header for 3xx reply.
Ret Code: ded92

### What is the exact error code you are receiving?
Please give the exact error code the app gives you.

### Steps to reproduce

1. When i load up luma-updater it tells me i can update to v2.5.
2.  click on update
3. error occurs

**Comment by KunoichiZ** [comment]
#53
