### ISSUE TITLE
Not able to download Luma3DS 10.2 using updater

### ISSUE THREAD

**Issue by DragRedSim** [KunoichiZ/lumaupdate#75]
### What model of system are you using?
- [ ] Old 3DS
- [ ] Old 3DS XL
- [ ] 2DS (non-XL)
- [x] New 3DS
- [ ] New 3DS XL
- [ ] New 2DS XL

### What is your current Luma3DS version?
If you are running an hourly version of Luma3DS, please manually update to a stable version as I will no longer deal with people who are using hourlies.

- [ ] Luma3DS v7.1 + boot9strap v1.0/v1.1
- [ ] Luma3DS v8.0 + boot9strap v1.2+
- [ ] Luma3DS v8.1 + boot9strap v1.2+
- [ ] Luma3DS v8.1.1 + boot9strap v1.2+
- [ ] Luma3DS v9.0 + boot9strap v1.2+
- [ ] Luma3DS v9.1 + boot9strap v1.2+
- [x] Luma3DS v10.0+ + boot9strap v1.2+ (10.1.3)

### What version of Luma Updater are you using?
- [ ] v2.0
- [ ] v2.1
- [ ] v2.1.1
- [ ] v2.1.2
- [ ] v2.2
- [ ] v2.3
- [ ] v2.4
- [x] v2.5

### How are you running Luma Updater?
- [ ] .cia
- [x] .3dsx + HBL/Rosalina

### What problems are you experiencing?
LumaUpdater is not receiving the correct information for the latest version (10.2) of Luma3DS. The “Latest version (Github):” value is blank, and the lower screen states “No release notes found for v”. It does state that a new stable version of Luma3DS is available, but pressing A locks the input and nothing occurs. Cannot even exit using the Home button; the only available input is to open the Rosalina menu and work from there.

### What is the exact error code you are receiving?
No error code displayed on screen.

### Steps to reproduce

1. Start up 3DS
2. Open Homebrew Menu (mapped to Download Play)
3. Open LumaUpdater

**Comment by KunoichiZ** [comment]
Try again. Also I don’t support the HBL version.

**Comment by DragRedSim** [comment]
Same issue on first relaunch, but it got the data correctly on second relaunch. Based on this, this seems to be a duplicate of #70 but does confirm that that issue is not necessarily related to proxy settings as I don’t run any on my 3DS.

**Comment by KunoichiZ** [comment]
Yeah I still don't know why that happens.

**Comment by BoltTheEmolga** [comment]
Had the same issue on Luma3DS v9.1, N3DSXL, LumaUpdate v2.5, .cia. Also worked on the third try specifically, like with OP.

Just confirming that this is not a v10+ exclusive thing.

**Comment by bingbong2** [comment]
im having a problem with updating luma can i please have some help

**Comment by KunoichiZ** [comment]
@bingbong2 create a new issue

**Comment by AwesomeLuigi** [comment]
I am having this same issue on a Old3DS with Luma3DS V10.2.1 & Boot9Strap V1.2 (10.1.3), using Luma Updater 2.5 and running it using a .cia file

How could of this happen?

**Comment by KunoichiZ** [comment]
@AwesomeLuigi I have no time to fix this issue. Any and all new issues regarding this will be closed.

**Comment by KunoichiZ** [comment]
Closing as v2.6 has been released.
