### ISSUE TITLE
Title ID conflicts with eShop title

### ISSUE THREAD

**Issue by enderghast13** [KunoichiZ/lumaupdate#76]
The Title ID of this application (00040000001DEB00) conflicts with that of the eShop title Mia's Picnic (USA). As such, both this application and the USA version of Mia's Picnic cannot be installed at the same time without manually changing the Title ID. Please change the Title ID of this application.

**Comment by KunoichiZ** [comment]
It can easily be changed by forking, changing the title ID, and building it yourself. I’m sorry but one tiny eShop title isn’t going to make me change the title ID.
