### ISSUE TITLE
Update from 2.3 manual

### ISSUE THREAD

**Issue by ghost** [KunoichiZ/lumaupdate#78]
Where can I find the manual to install, update or upgrade the Luma?

**Comment by KunoichiZ** [comment]
Install the CIA yourself. #53

**Comment by ghost** [comment]
Where is the manual to install it is what I'm asking. No link anywhere not even in #53

**Comment by KunoichiZ** [comment]
@thejoker3000 There is no manual. Use FBI to install the v2.5 CIA.
