### ISSUE TITLE
Luma wont update

### ISSUE THREAD

**Issue by maeday5615** [KunoichiZ/lumaupdate#80]
### What model of system are you using?
- [ ] Old 3DS
- [x] Old 3DS XL
- [ ] 2DS (non-XL)
- [ ] New 3DS
- [ ] New 3DS XL
- [ ] New 2DS XL

### What is your current Luma3DS version?
If you are running an hourly version of Luma3DS, please manually update to a stable version as I will no longer deal with people who are using hourlies.

- [ ] Luma3DS v7.1 + boot9strap v1.0/v1.1
- [ ] Luma3DS v8.0 + boot9strap v1.2+
- [ ] Luma3DS v8.1 + boot9strap v1.2+
- [ ] Luma3DS v8.1.1 + boot9strap v1.2+
- [ ] Luma3DS v9.0 + boot9strap v1.2+
- [ x] Luma3DS v9.1 + boot9strap v1.2+
- [ ] Luma3DS v10.0+ + boot9strap v1.2+

### What version of Luma Updater are you using?
- [ ] v2.0
- [ ] v2.1
- [ ] v2.1.1
- [ ] v2.1.2
- [ ] v2.2
- [x ] v2.3
- [ ] v2.4
- [ ] v2.5

### How are you running Luma Updater?
- [x] .cia
- [ ] .3dsx + HBL/Rosalina

### What problems are you experiencing?
Please tell us what problems you are facing. When I try to update the luma updater it crashes and when I skip that update and try to update luma it says im not connected to the Internet but the Internet is working fine on the console 

### What is the exact error code you are receiving?
Please give the exact error code the app gives you. It isn't giving me an error code

### Steps to reproduce

1.  Go to the luma installer
2. Skip the luma update
3. Try and update it and I get the message

**Comment by maeday5615** [comment]
![20201118_145149](https://user-images.githubusercontent.com/74668256/99547680-b9505f80-29af-11eb-877b-cf4bd29b70de.jpg)

This is the error I get when I try updating the luma updater

**Comment by MFGookey** [comment]
+1 same hardware, same Luma Updater version.
The error message on the lower screen reads: FATAL: Could not get Location header for 3xx reply
Ret code: ded92

**Comment by BornSupercharged** [comment]
https://github.com/KunoichiZ/lumaupdate/releases

Download the latest lumaupdater.cia and throw it a folder named cias on your microSD card.
Put the microSD card back into your 3DS. Then open FBI app, navigate SD -> cias -> lumaupdater.cia -> Install CIA
Then power off and back on.

Now open Luma Updater and apply the latest version. 

Worked for me just now.

**Comment by KunoichiZ** [comment]
#53

**Comment by maeday5615** [comment]
It downloaded and the update went fine but some of the apps still don't work which is the whole reason I updated 
![16057283454609205600547717287345](https://user-images.githubusercontent.com/74668256/99579195-c2ecbe00-29d5-11eb-8b99-4693aac85692.jpg)

**Comment by MFGookey** [comment]
Thanks for the replies, guys.  I ended up doing the cia process on my own, but wanted to make sure the bug got reported if it were fixable.

**Comment by KunoichiZ** [comment]
@MFGookey The bug is fixable and was already fixed in v2.5.
@maeday5615 That’s not my problem. Bring that up to the Luma3DS devs.
