### ISSUE TITLE
[REQUEST] BAX support.

### ISSUE THREAD

**Issue by jeffyjeffy1023** [KunoichiZ/lumaupdate#81]
(more info on BAX: https://gbatemp.net/threads/release-bax-boot-animations-for-your-3ds.497717/)

Since the updater (by default) overwrites boot.firm whenever it updates Luma, it breaks any existing BAX install.
The way I'd fix this is add a built-in config menu if possible, or at least some sorta lumaupdater-config.txt on SD root, so that we can change the boot.firm path after the updater is compiled. (e.g. SD:\bax\boot.firm instead of just SD:\boot.firm)

Like maybe a toggle?

If it were done through a .txt on SD root, I'd format it like so:
_____________________________________________________________________
\\Luma Updater configuration file. Check the wiki for more info.  |
                                                                                                        |
useBAXpath [Y] (or N for no                                                            |
                                                                                                        |
____________________________________________________________________/

**Comment by KunoichiZ** [comment]
You should be updating Luma manually in that case. That's not a high priority right now. If you know how, you can feel free to make a PR.
