### ISSUE TITLE
Can't Update to 10.2+

### ISSUE THREAD

**Issue by Duff-McW** [KunoichiZ/lumaupdate#87]
### What model of system are you using?
- [ ] Old 3DS
- [ ] Old 3DS XL
- [ ] 2DS (non-XL)
- [ ] New 3DS
- [x ] New 3DS XL
- [ ] New 2DS XL

### What is your current Luma3DS version?
If you are running an hourly version of Luma3DS, please manually update to a stable version as I will no longer deal with people who are using hourlies.

- [ ] Luma3DS v7.1 + boot9strap v1.0/v1.1
- [ ] Luma3DS v8.0 + boot9strap v1.2+
- [ ] Luma3DS v8.1 + boot9strap v1.2+
- [ ] Luma3DS v8.1.1 + boot9strap v1.2+
- [ ] Luma3DS v9.0 + boot9strap v1.2+
- [ ] Luma3DS v9.1 + boot9strap v1.2+
- [x ] Luma3DS v10.0+ + boot9strap v1.2+

### What version of Luma Updater are you using?
- [ ] v2.0
- [ ] v2.1
- [ ] v2.1.1
- [ ] v2.1.2
- [ ] v2.2
- [ ] v2.3
- [ ] v2.4
- [x] v2.5

### How are you running Luma Updater?
- [x] .cia
- [ ] .3dsx + HBL/Rosalina

### What problems are you experiencing?
Given the error message  "Could not obtain update details. Check that the console is connected to the Internet." The console is connected to the Internet, at Sys 11.13.0-45U.

### What is the exact error code you are receiving?
"Could not obtain update details. Check that the console is connected to the Internet."

### Steps to reproduce

1. Turn on N3DSXL System.
2. Open Luma Updater from folder on Home Menu.
3. Allow Luma Updater to load, get dropped into error message.

**Comment by KunoichiZ** [comment]
Closing; duplicate issue.
