### ISSUE TITLE
 "could not obtain update details"

### ISSUE THREAD

**Issue by halpz** [KunoichiZ/lumaupdate#89]
### What model of system are you using?
- [ ] Old 3DS
- [x ] Old 3DS XL
- [ ] 2DS (non-XL)
- [ ] New 3DS
- [ ] New 3DS XL
- [ ] New 2DS XL

### What is your current Luma3DS version?
If you are running an hourly version of Luma3DS, please manually update to a stable version as I will no longer deal with people who are using hourlies.

- [ ] Luma3DS v7.1 + boot9strap v1.0/v1.1
- [ ] Luma3DS v8.0 + boot9strap v1.2+
- [ ] Luma3DS v8.1 + boot9strap v1.2+
- [ ] Luma3DS v8.1.1 + boot9strap v1.2+
- [ ] Luma3DS v9.0 + boot9strap v1.2+
- [ ] Luma3DS v9.1 + boot9strap v1.2+
- [x ] Luma3DS v10.0+ + boot9strap v1.2+

### What version of Luma Updater are you using?
- [ ] v2.0
- [ ] v2.1
- [ ] v2.1.1
- [ ] v2.1.2
- [ ] v2.2
- [ ] v2.3
- [ ] v2.4
- [x ] v2.5

### How are you running Luma Updater?
- [x ] .cia
- [ ] .3dsx + HBL/Rosalina

### What problems are you experiencing?

"could not obtain update details"

### Steps to reproduce

1. connect to wifi
2. open luma updater
3. can't dind update data

**Comment by halpz** [comment]
I believe it's because this page is no longer there:

http://astronautlevel2.github.io/

**Comment by halpz** [comment]
Shall we all uninstall it then @KunoichiZ ?

**Comment by KunoichiZ** [comment]
@halpz No, wait for me to release a new version.
