### ISSUE TITLE
black screen after update hourly version

### ISSUE THREAD

**Issue by samfadel** [KunoichiZ/lumaupdate#9]
I get a problem today when update to last hourly version when restart o3ds or o3ds xl(i have both) i get black screen even without sd card but when restore boot.frim.bak every thing back normal (replace ctr nand boot.frim also) because it update both (sd and ctrnand boot.frim)

**Comment by samfadel** [comment]
payload type:sighax
current version : 7.1-c73fec46
lastest hourly:90f29af
luma update v2.1

**Comment by RinMaru** [comment]
yea had the same issue same setup as you on my N3DSXL

**Comment by KunoichiZ** [comment]
The latest hourly doesn't work at the moment. This is not a bug with Luma Updater.
