### ISSUE TITLE
Luma3ds updater 2.6 Update Failed 

### ISSUE THREAD

**Issue by AwesomeLuigi** [KunoichiZ/lumaupdate#92]
### What model of system are you using?
- [V] Old 3DS
- [ ] Old 3DS XL
- [ ] 2DS (non-XL)
- [ ] New 3DS
- [ ] New 3DS XL
- [ ] New 2DS XL

### What is your current Luma3DS version?
If you are running an hourly version of Luma3DS, please manually update to a stable version as I will no longer deal with people who are using hourlies.

- [ ] Luma3DS v7.1 + boot9strap v1.0/v1.1
- [ ] Luma3DS v8.0 + boot9strap v1.2+
- [ ] Luma3DS v8.1 + boot9strap v1.2+
- [ ] Luma3DS v8.1.1 + boot9strap v1.2+
- [ ] Luma3DS v9.0 + boot9strap v1.2+
- [ ] Luma3DS v9.1 + boot9strap v1.2+
- [V] Luma3DS v10.0+ + boot9strap v1.2+

### What version of Luma Updater are you using?
- [ ] v2.0
- [ ] v2.1
- [ ] v2.1.1
- [ ] v2.1.2
- [ ] v2.2
- [ ] v2.3
- [ ] v2.4
- [V] v2.5
- [ ] v2.6

### How are you running Luma Updater?
- [V] .cia
- [ ] .3dsx + HBL/Rosalina

### What problems are you experiencing?
Please tell us what problems you are facing.

I was going to update Luma3DS using the Updater and the 2.6 update for the Updater is available and tried updating the updater and gives me the Update Failed issue

### What is the exact error code you are receiving?
Please give the exact error code the app gives you.

Ret code : d8a08002 
FATAL : Cannot write CIA data to handle 
Reason for Failure : CIA INSTALL FAILED

### Steps to reproduce

1. Shutdown the 3DS 
2. Take out the SD Card 
3. Download the Cia from the Lumaupdate Github page and put it in the SD Card and Reboot the 3DS and Install CIA and Start the App.

**Comment by AwesomeLuigi** [comment]
It just gave me this issue when trying to update the Lumaupdater and it refused to work

**Comment by KunoichiZ** [comment]
Read #53.
