### ISSUE TITLE
2.6 built with wrong git version 

### ISSUE THREAD

**Issue by MechanicalDragon0687** [KunoichiZ/lumaupdate#93]
### What version of Luma Updater are you using?

- [X ] v2.6

### How are you running Luma Updater?
- [X ] .cia

### What problems are you experiencing?
version shows 2.5 internally and attempts to update itself to 2.6 upon launch.

### Steps to reproduce

1. install cia
2. open luma updater
3. observe the app attempt to update to 2.6

additionally upon allowing it to try to update, it will fail to install the cia with error code D8A08002

**Comment by MechanicalDragon0687** [comment]
Ignoring the update prompt allows it to download current luma

**Comment by KunoichiZ** [comment]
I'll fix the build version tomorrow, that's my bad. Also, please read #53 as you have to manually install the cia.

**Comment by MechanicalDragon0687** [comment]
I am aware it must be manually installed from 2.5, are you saying that even 2.6 cant update itself? if so, why even have that option in it?

**Comment by KunoichiZ** [comment]
@MechanicalDragon0687 2.6 should be able to update itself. There are no other versions to test that with though.

**Comment by KunoichiZ** [comment]
Closing as I've fixed the release.
