### ISSUE TITLE
LumaUpdate 2.6 detects update for itself where none exists

### ISSUE THREAD

**Issue by eku** [KunoichiZ/lumaupdate#94]
### What model of system are you using?
- [ ] Old 3DS
- [ ] Old 3DS XL
- [ ] 2DS (non-XL)
- [ ] New 3DS
- [x] New 3DS XL
- [ ] New 2DS XL

### What is your current Luma3DS version?
If you are running an hourly version of Luma3DS, please manually update to a stable version as I will no longer deal with people who are using hourlies.

- [ ] Luma3DS v7.1 + boot9strap v1.0/v1.1
- [ ] Luma3DS v8.0 + boot9strap v1.2+
- [ ] Luma3DS v8.1 + boot9strap v1.2+
- [ ] Luma3DS v8.1.1 + boot9strap v1.2+
- [ ] Luma3DS v9.0 + boot9strap v1.2+
- [ ] Luma3DS v9.1 + boot9strap v1.2+
- [x] Luma3DS v10.0+ + boot9strap v1.2+

### What version of Luma Updater are you using?
- [ ] v2.0
- [ ] v2.1
- [ ] v2.1.1
- [ ] v2.1.2
- [ ] v2.2
- [ ] v2.3
- [ ] v2.4
- [ ] v2.5
- [x] v2.6

### How are you running Luma Updater?
- [ ] .cia
- [x] .3dsx + HBL/Rosalina

### What problems are you experiencing?

I have manually installed the update of the 3dsx to 2.6. When I start it, it says there is a newer version 2.6, which is not true.

### What is the exact error code you are receiving?

```An update for LumaUpdater is available!```

```Release notes for vv2.6 ```

Please note the double `v`. Might be the reason for the problem.

### Steps to reproduce

1. Unzip the v2.6 version to root of SD card
2. Start the 3dsx version
3.

**Comment by eku** [comment]
Looks like the ZIP contains the version **2.5** of the 3dsx file!

**Comment by KunoichiZ** [comment]
Yep, I'm aware of this. It doesn't contain the v2.5 file but I forgot to change the version number.
