### ISSUE TITLE
Luma3DS Updater hangs when starting up

### ISSUE THREAD

**Issue by ghost** [KunoichiZ/lumaupdate#95]
### What model of system are you using?
- [ ] Old 3DS
- [ ] Old 3DS XL
- [X] 2DS (non-XL)
- [ ] New 3DS
- [ ] New 3DS XL
- [ ] New 2DS XL

### What is your current Luma3DS version?
If you are running an hourly version of Luma3DS, please manually update to a stable version as I will no longer deal with people who are using hourlies.

- [ ] Luma3DS v7.1 + boot9strap v1.0/v1.1
- [ ] Luma3DS v8.0 + boot9strap v1.2+
- [ ] Luma3DS v8.1 + boot9strap v1.2+
- [ ] Luma3DS v8.1.1 + boot9strap v1.2+
- [ ] Luma3DS v9.0 + boot9strap v1.2+
- [ ] Luma3DS v9.1 + boot9strap v1.2+
- [X] Luma3DS v10.0+ + boot9strap v1.2+

### What version of Luma Updater are you using?
- [ ] v2.0
- [ ] v2.1
- [ ] v2.1.1
- [ ] v2.1.2
- [ ] v2.2
- [ ] v2.3
- [ ] v2.4
- [ ] v2.5
- [X] v2.6

### How are you running Luma Updater?
- [X] .cia
- [ ] .3dsx + HBL/Rosalina

### What problems are you experiencing?
Please tell us what problems you are facing.

When starting up Luma3DS Updater from the HOME Menu, the system hangs when it's "Checking for an updated updater..."
until you hold the POWER Button to turn it off.

### What is the exact error code you are receiving?
Please give the exact error code the app gives you.

No Error Code given.

### Steps to reproduce

1. Launch Luma3DS Updater from the HOME Menu.
2. Profit

**Comment by KunoichiZ** [comment]
I can't replicate the issue. Try again.

**Comment by ghost** [comment]
My apologizes, I've noticed that the 2DS Date and Time were incorrect which caused Luma3DS Updater to hang. I've fixed the Date and Time and now Luma3DS Updater boots normally. I have no idea that the cause of this issue was that the Date and Time were wrong.
