### ISSUE TITLE
Continuous MD5 check error

### ISSUE THREAD

**Issue by kyoukq** [KunoichiZ/lumaupdate#97]
### What model of system are you using?
- [ ] Old 3DS XL
- [ ] Old 3DS
- [ ] 2DS (non-XL)
- [ ] New 3DS
- [x] New 3DS XL
- [ ] New 2DS XL

### What is your current Luma3DS version?
If you are running an hourly version of Luma3DS, please manually update to a stable version as I will no longer deal with people who are using hourlies.

- [ ] Luma3DS v7.1 + boot9strap v1.0/v1.1
- [ ] Luma3DS v8.0 + boot9strap v1.2+
- [ ] Luma3DS v8.1 + boot9strap v1.2+
- [ ] Luma3DS v8.1.1 + boot9strap v1.2+
- [ ] Luma3DS v9.0 + boot9strap v1.2+
- [ ] Luma3DS v9.1 + boot9strap v1.2+
- [x] Luma3DS v10.0+ + boot9strap v1.2+

### What version of Luma Updater are you using?
- [ ] v2.0
- [ ] v2.1
- [ ] v2.1.1
- [ ] v2.1.2
- [ ] v2.2
- [ ] v2.3
- [ ] v2.4
- [ ] v2.5
- [x] v2.6

### How are you running Luma Updater?
- [x] .cia
- [ ] .3dsx + HBL/Rosalina

### What problems are you experiencing?

Whenever I try to update luma I get an MD5 mismatch on the 2nd check consistently. The download also happens instantly on subsequent attempts, so it would seem it doesn't delete the corrupted files when the check fails and just checks it again without redownloading. I tried restarting the 3ds and the application multiple times. I could not find where the downloads are stored to try manually deleting it.

EDIT: It seems others are having the same issue, so I'm assuming the issue has something to do with the server check itself rather than a corrupted download.

### What is the exact error code you are receiving?

No error code.

### Steps to reproduce

1. Try to update with a corrupted file already in the directory

**Comment by ToastyKip** [comment]
I'm also having this issue. 
The device I'm using is an Old 3DS XL, and the updater menu says my Luma installation is on 10.2. I'm lacking an SD card reader, so I thought to update to 10.2.1 this way, but I'm stuck for now because of this unfortunately.

**Comment by futurelucas4502** [comment]
Hi there same issue here I've included a few screenshots below to hopefully show the issue I'm having as well as other information which may or may not be relevant:
![20211224_024644630.jpg](https://user-images.githubusercontent.com/48055553/147310781-40b19c10-a6ba-438f-b335-1cf8946d565d.jpg)
![20211224_025220492.jpg](https://user-images.githubusercontent.com/48055553/147310790-7874f586-c068-433e-8fe3-afed8af716f3.jpg)
![20211224_024704108.jpg](https://user-images.githubusercontent.com/48055553/147310802-a39c90b0-7bc3-4e09-9fa9-ec0562ee843e.jpg)

**Comment by RoXYTheNeko** [comment]
Same problem with 3DS XL on Sys 11.14.0-46E and Luma Updater 2.4

**Comment by futurelucas4502** [comment]
@RoXYTheNeko your on version 2.4 so you have a different problem you have to manually update lumaupdater to version 2.6 see #53

If it still doesn't work then u have the same problem as us

**Comment by dylanr2003** [comment]
im having the same issue. made a github for this, even. Would love to know if anyone finds the fix

**Comment by jasonridesabike** [comment]
Same issue on a new 3ds.

![image](https://user-images.githubusercontent.com/5529522/147533991-69499cc0-26e4-455e-ba68-6ddedb28c7f1.jpg)

![image](https://user-images.githubusercontent.com/5529522/147534098-3cac3aea-f21d-48c3-ba3d-0a743594a70d.jpg)

**Comment by dinckelman** [comment]
Can replicate this issue with the exact same environment as the original poster

**Comment by TehH4rRy** [comment]
Can confirm exact same issue for me too.

**Comment by ToastedEggplant** [comment]
Same here

**Comment by dehydratedkidney** [comment]
having this same issue, please lmk if anything changes or fixes thank you :)

**Comment by b000rg** [comment]
Issue is present for me as well. I'm wanting to update my system version but I'm hesitant to until I'm sure I'm running the latest version of Luma.

update: I was able to get Luma3DS updated to v10.2.1 using Universal Updater, just FYI for those looking to get your CFW updated.

**Comment by project-shasta** [comment]
Updating Luma3DS via Universal Updater worked fine, am on Version 10.2.1 now. The Updater is also happy now.

**Comment by speed47** [comment]
FWIW, FBI's update system also fails the MD5 check, so something changed somewhere (github ? location of the MD5 reference file that we're trying to check the downloaded payload against ?)

EDIT: The `Integrity check #2` is a check against the ETag of the HTTP response:

```
$ curl -sLI --http1.1 https://github.com/LumaTeam/Luma3DS/releases/download/v10.2.1/Luma3DSv10.2.1.zip  |& grep ETag
ETag: "0x8D9BA0160D81308"
$
```

My guess would be that the ETag format has changed.

EDIT2: Oh, well, got it, we had one chance out of 16 to have this bug: the ETag format doesn't print the leftmost zeroes, i.e. if it was `0x08D9BA0160D81308` then the algorithm would have parsed it correctly. @KunoichiZ if I proposed a patch, would you merge it?

EDIT3: Okay, it's uglier than this, the ETag format does have changed, and the MD5 can no longer be inferred from it. The bad news it that it makes LumaUpdater actually read uninitialized memory, because the ETag is now shorted than what is expected. The good news is that the MD5 is now available through another HTTP header (Content-MD5) that is bas64 encoded. In any case, my PR proposition still stands.

**Comment by micheleg95** [comment]
> 

Hi, same problem. 
How can i solve it ?
Do you have a .cia file with this fix?

Thanks

**Comment by KunoichiZ** [comment]
Why are people still using this? 3ds.hacks.guide has a better method to updating Luma now. LumaUpdater isn't even a part of the guide anymore. Closing this as all developement has stopped on this, in case it wasn't obvious.
