### ISSUE TITLE
Download of 10.2.1 version failure - MD5 Mismatch between server's and local file!

### ISSUE THREAD

**Issue by GhostBelmont** [KunoichiZ/lumaupdate#98]
### What model of system are you using?
- [ ] Old 3DS
- [X] Old 3DS XL
- [ ] 2DS (non-XL)
- [ ] New 3DS
- [ ] New 3DS XL
- [ ] New 2DS XL

### What is your current Luma3DS version?
If you are running an hourly version of Luma3DS, please manually update to a stable version as I will no longer deal with people who are using hourlies.

- [ ] Luma3DS v7.1 + boot9strap v1.0/v1.1
- [ ] Luma3DS v8.0 + boot9strap v1.2+
- [ ] Luma3DS v8.1 + boot9strap v1.2+
- [ ] Luma3DS v8.1.1 + boot9strap v1.2+
- [ ] Luma3DS v9.0 + boot9strap v1.2+
- [ ] Luma3DS v9.1 + boot9strap v1.2+
- [X] Luma3DS v10.0+ + boot9strap v1.2+

### What version of Luma Updater are you using?
- [ ] v2.0
- [ ] v2.1
- [ ] v2.1.1
- [ ] v2.1.2
- [ ] v2.2
- [ ] v2.3
- [ ] v2.4
- [ ] v2.5
- [X] v2.6

### How are you running Luma Updater?
- [X] .cia
- [ ] .3dsx + HBL/Rosalina

### What problems are you experiencing?
Please tell us what problems you are facing.

Update for version 10.2.1 failure

### What is the exact error code you are receiving?
Please give the exact error code the app gives you.

Integrity check  #2 [ERR] - MD5 mismatch between server's and local file! FATAL Could not get sighax payload.

### Steps to reproduce

1. Open the app Luma3ds Updater
2. Choose the option install latest update
3. Choose option A + X to enable downloading

**Comment by KunoichiZ** [comment]
Why are people still using this? 3ds.hacks.guide has a better method to updating Luma now. LumaUpdater isn't even a part of the guide anymore. Closing this as all developement has stopped on this, in case it wasn't obvious.
