### ISSUE TITLE
MDS Mismatch between server's and local file!

### ISSUE THREAD

**Issue by R9anSmart** [KunoichiZ/lumaupdate#99]
### What model of system are you using?
- [ ] Old 3DS
- [ ] Old 3DS XL
- [ ] 2DS (non-XL)
- [ ] New 3DS
- [.] New 3DS XL
- [ ] New 2DS XL

### What is your current Luma3DS version?
If you are running an hourly version of Luma3DS, please manually update to a stable version as I will no longer deal with people who are using hourlies.

- [ ] Luma3DS v7.1 + boot9strap v1.0/v1.1
- [ ] Luma3DS v8.0 + boot9strap v1.2+
- [ ] Luma3DS v8.1 + boot9strap v1.2+
- [ ] Luma3DS v8.1.1 + boot9strap v1.2+
- [ ] Luma3DS v9.0 + boot9strap v1.2+
- [ ] Luma3DS v9.1 + boot9strap v1.2+
- [.] Luma3DS v10.0+ + boot9strap v1.2+

### What version of Luma Updater are you using?
- [ ] v2.0
- [ ] v2.1
- [ ] v2.1.1
- [ ] v2.1.2
- [ ] v2.2
- [ ] v2.3
- [ ] v2.4
- [ ] v2.5
- [.] v2.6

### How are you running Luma Updater?
- [.] .cia
- [ ] .3dsx + HBL/Rosalina

### What problems are you experiencing?
Please tell us what problems you are facing.

### What is the exact error code you are receiving?
Please give the exact error code the app gives you.

Sv10.2.1.zip Download progress: 364996 364996 Download complete! Size: 364996 Integrity check #1 OK

Integrity check #1 [ok]
Integrity check #2 [ERR]

MDS Mismatch between server's and local file!
FATAL
Could not get sighax payload...

![PXL_20220219_132020625](https://user-images.githubusercontent.com/100030137/154803269-eeefa1eb-bb2a-40bb-9422-13cfb0cf0c0f.jpg)

### Steps to reproduce

1. Open lumaupdater
2.  Run update
3. Fails

![PXL_20220219_134258667 MP~2](https://user-images.githubusercontent.com/100030137/154803328-69b130ab-ecf6-4dce-906e-90a9a8ab16b4.jpg)

**Comment by KunoichiZ** [comment]
Why are people still using this? 3ds.hacks.guide has a better method to updating Luma now. LumaUpdater isn't even a part of the guide anymore. Closing this as all developement has stopped on this, in case it wasn't obvious.
